### ISSUE TITLE
Data to be released in CSV format (feature request)

### ISSUE THREAD

**Issue by nelsonmau** [ruggsea/llm_italian_poll_scraper#1]
Not only in [json](https://github.com/ruggsea/llm_italian_poll_scraper/blob/main/italian_polls.jsonl)

**Comment by aborruso** [comment]
> Not only in [json](https://github.com/ruggsea/llm_italian_poll_scraper/blob/main/italian_polls.jsonl?rgh-link-date=2024-09-05T18%3A36%3A40Z)

I want to add a note. Not to do the super precise one. This is a [jsonlines](https://jsonlines.org/) not a json. The jsonline is somewhat the CSV of jsons, where every single line is a json object. It is a kind of flattened json, which even in visualization looks almost like a comma separated values.

> The difference is a world of frustration. That first beautiful example in JSON lines, one logical object per line. Their order is implicit in the line numbering of the file. The other 3 are *pure* JSON. But that purity comes at a cost, all three are semantically identical, but the classic UNIX tools like `grep`, `wc`, `diff` couldn’t care less about JSON’s whitespace ideology. For example, `wc -l` would give you 3 different answers for the pure JSON none of them equal to the number of objects in the list. That’s fine if you’re going to be loading this file into your program as a configuration, but if you are loading data for the love of your own sanity use JSON lines. With JSON lines you’ll get all sorts of free information like `wc -l` giving you the list length and `grep` returning single, usable, JSON objects.
>
>There are plenty of resources for loading newline delimited JSON, the easiest is to remember is [jsonlines.org](http://jsonlines.org/), it also gives some other nice features and info on the origin of the term and preferred extension (`.jsonl`). These days some programming languages have packages for loading JSON lines, even though it is usually easy to do using their standard JSON and line reading primitives.

Taken from a post I have long kept in my "delicious": https://zxvf.org/post/jq-as-grep/

**Comment by ruggsea** [comment]
CSV format output added in commit f7ec039

**Comment by nelsonmau** [comment]
scusatemi se ho usato l'inglese in questa issue, pensavo che voleste fare tutto in eng :-) 

invece complimenti per questo passaggio nell'articolo, giuro che non la prendo sul personale! :rofl: 

![image](https://github.com/user-attachments/assets/2c5a158d-f45e-41d1-a439-eee6c90ddd74)
