### ISSUE TITLE
Controllo di debug interessante: se la somma fa 100

### ISSUE THREAD

**Issue by aborruso** [ruggsea/llm_italian_poll_scraper#10]
Caro @ruggsea ,
un altro controllo interessante, che fa scoprire cose è quello del controllo del totale.

Se ad esempio filtri i sondaggi in cui ci sono almeno 5 partiti + altri (quindi diciamo >= 6), su 1150 sondaggi, soltanto 162 sondaggi danno un totale di 100.
Lo so, dipende anche da come vengono estratti i partiti, però ti dà l'occasione di scoprire come una somma a 199.
Perché ci sono domande come quella di sotto, che è nazionale, ma sia presentata in forma diversa dalle altre e diciamo di tipo diverso.

2023-03-06 │ Quorum │ Sky TG24 │ Osservatorio Italia

![image](https://github.com/user-attachments/assets/4e647b99-6832-476f-8797-6e2a78ba6a7b)

**Comment by ruggsea** [comment]
Questo sondaggio specifico è stato filtrato automaticamente dall'llm a questo giro, andranno fatti ulteriori controlli
