### ISSUE TITLE
Nota su nuovi dati

### ISSUE THREAD

**Issue by aborruso** [ruggsea/llm_italian_poll_scraper#11]
Caro @ruggsea ,
nella nuova estrazione, ci sono diverse righe in cui il valore di tutti i partiti è nullo.

Sono circa un centinaio.

Baci

**Comment by aborruso** [comment]
Perché è vuoto il `text`

**Comment by ruggsea** [comment]
Dovrebbe essere stato risolto con 59c1cd8f943f272e1db0455e419f6367ef804a1b , bisogna aspettare il prossimo scrape completo per controllare
