### ISSUE TITLE
nomi campo "normalizzati"

### ISSUE THREAD

**Issue by aborruso** [ruggsea/llm_italian_poll_scraper#4]
Caro Ruggero,
non mi odiare. Stasera mi vengono idee.

I nomi di campo human readable mi fanno morire. Se si passa da wide a long #2, passerei tutto a snake_case

```
row
data_inserimento
realizzatore
committente
titolo
text
domanda
national_poll
partito
valore
```

E anche se non si passa da wide a long, normalizzerei almeno i nomi di campo che non sono partiti.

**Comment by ruggsea** [comment]
I nomi di campo in questa prima versione sono uguali a come risultano a schermo sul sito originale: anche se non mi piacciono, ho pensato che massimizzano la familiarità del dato agli addetti ai lavori. Propongo di normalizzarli per la versione "long" del dataset, quella più "tidy"

**Comment by ruggsea** [comment]
Sempre aggiunto riferimento in 20d8cd150ef5d3e31126a3006094176b48214184
