### ISSUE TITLE
Normalizzatore "realizzatore"

### ISSUE THREAD

**Issue by aborruso** [ruggsea/llm_italian_poll_scraper#7]
Caro @ruggsea ,
nei miei meta, ho aggiunto una nuova colonna `realizzatore_normalizzato`, creata a valle di confronto fuzzy, per i casi di sotto.

La grandissima parte si risolve con lowercase e clean-whitespace. Ma così è più divertente.

![image](https://github.com/user-attachments/assets/fdf485b9-ca6f-4e3c-928c-9c1865abfcd9)

**Comment by ruggsea** [comment]
Sempre chiuso con riferimento a repo ondata
