### ISSUE TITLE
Valori negativi

### ISSUE THREAD

**Issue by aborruso** [ruggsea/llm_italian_poll_scraper#8]
Caro @ruggsea,
ho notato strani valori negativi.

Avviene per il sondaggio di sotto. In questo ci sono tre domande, in cui quella da prendere (se ho capito il tuo obiettivo) è la 1.
Mentre viene presa la 3, che una domanda di confronto rispetto a un anno prima, quindi ci possono essere valori negativi.

Lato "mio" sto rimuovendo qualsiasi sondaggio contiene valori negativi.

Buonanotte

![image](https://github.com/user-attachments/assets/35e030db-f431-4308-870f-da82ed9183b1)

**Comment by ruggsea** [comment]
Cercato di aggiustarlo con f65b5a67fc78073b2a37a2810848fe8a1dbe07e2 , si vedrà nel prossimo scrape da zero
